---
- hosts: localhost
  vars:
    dotfiles: ~/dotfiles
  tasks:
    - file: src={{ dotfiles }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc
        - gitconfig
    - git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

    - homebrew: state=present name=ctags install_options="--with-exuberant-ctags"
    - homebrew: name={{ item }}
      with_items:
        - imagemagick
        - ack
        - npm
        - postgresql
        - redis
        - erlang
        - leiningen
        - bash-completion
        - https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb

    - shell: ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
    - shell: ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents

    - shell: curl -sSL https://get.rvm.io | bash -s stable --ruby creates=~/.rvm
    - gem: name={{ item }} state=present
      with_items:
        - bundler
        - haml-lint
        - ruby-lint
        - rubocop
        - sass

    - npm: name={{ item }} global=yes
      with_items:
        - bower
        - js-yaml
        - jsxhint
        - eslint
        - jsonlint
        - grunt-cli

    - easy_install: name=pip
      sudo: yes
    - pip: name={{ item }}
      sudo: yes
      with_items:
        - pylint

    - lineinfile: dest="~/.bash_profile" state=present
                  line="set -o vi"
