---
- hosts: all
  vars:
    dotfiles: /var/tmp/dotfiles

  pre_tasks:
    - apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        # - ack
        - ack-grep
        - exuberant-ctags
        - vim
        - git
        - curl
        # - python-setuptools
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - tmux
        # - ocaml-nox
        # - opam

  tasks:
    - easy_install: name=pip
      sudo: yes

    - pip: name={{ item }} state=latest
      sudo: yes
      with_items:
        - pylint
        #- bashate
        # - git+https://github.com/docker/fig.git#egg=fig
        # - fig
        # - "https://github.com/docker/fig/archive/master.zip"
      tags: python

    - file: src={{ dotfiles }}/{{ item }} dest=~/.{{ item }} state=link
      sudo: yes
      sudo_user: "{{ ansible_user_id }}"
      with_items:
        - vimrc
        - gitconfig

    - git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
      sudo: yes
      sudo_user: "{{ ansible_user_id }}"
    # - shell: vim +PluginInstall +qall

    - gem: name={{ item }} state=latest user_install=no
      sudo: yes
      with_items:
        - haml-lint
        - ruby-lint
        - rubocop
        - sass
      tags: [ruby]

    - npm: name={{ item }} global=yes state=latest
      sudo: yes
      with_items:
        - bower
        - js-yaml
        - eslint # NOTE: http://eslint.org/docs/configuring/ for enabling jsx
        - jsonlint
        - grunt-cli
        - flow-bin

    - lineinfile: dest="~/.bash_profile" state=present create=yes
        line="set -o vi"

    - lineinfile: dest="~/.bash_profile" state=present create=yes
        line="export PS1='$(__git_ps1) \w\$ '"
