---
- hosts: all
  vars:
    dotfiles: /var/tmp/dotfiles
    rvm1_rvm_check_for_updates: no
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_bin_path: '{{ rvm1_install_path }}/rubies/default/bin'

  pre_tasks:
    - apt: name={{ item }} state=latest
      sudo: yes
      with_items:
        # - ack
        - ack-grep
        - exuberant-ctags
        - vim
        - git
        - npm
        - curl
        # - python-setuptools
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - tmux

  roles:
      - { role: rvm_io.rvm1-ruby, tags: ruby }

  post_tasks:
    - easy_install: name=pip
      sudo: yes

    - pip: name={{ item }} state=latest
      sudo: yes
      with_items:
        - pylint
        - bashate
        # - git+https://github.com/docker/fig.git#egg=fig
        # - fig
        # - "https://github.com/docker/fig/archive/master.zip"
      tags: python

    - file: src={{ dotfiles }}/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc
        - gitconfig

    - git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
    # - shell: vim +PluginInstall +qall

    - gem: name={{ item }} state=present executable='{{ rvm1_bin_path }}/gem' user_install=no
      with_items:
        - haml-lint
        - ruby-lint
        - rubocop
        - sass
      tags: [ruby]

    - npm: name={{ item }} global=yes state=latest
      sudo: yes
      with_items:
        - bower
        - js-yaml
        - jsxhint
        - eslint
        - jsonlint
        - grunt-cli

    - lineinfile: dest="~/.bash_profile" state=present
        line="set -o vi"

    - lineinfile: dest="~/.bash_profile" state=present
        line="export PS1='$(__git_ps1) \w\$ '"
